version: "3.9"

services:
  redis:
    image: redis:alpine
    restart: always

  pyapp:
    image: ghcr.io/rejiconc/weather-pyapp:latest
    build: .
    depends_on:
      - redis
    restart: always
    ports:
      - "80:5000"

